# Uncomment this line to define a global platform for your project
platform :ios, '8.0'


use_frameworks!

target 'DailyPicChallenge' do

pod 'Bond', '~> 3.7'

end

target 'DailyPicChallengeTests' do

end

